### ISSUE TITLE
Consider optimizing small subset of zero-arity cases

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#164]
There's a small subset of cases that I think we could optimize even further, depending on how crazy we want to get. If:

- [x] the method we're optimizing has an arity of 0 (no args)
- [x] the result object can be converted to Ruby source code with no loss of information, e.g. it is both frozen and one of: `nil`, a boolean, a small int (`Fixnum`?), a symbol, or a string
  - (or maybe an array or hash containing only those elements? what about nested arrays and hashes that are all frozen?)

Then when the method is first called, instead of inserting the value into our method's cache we can actually just rewrite the entire method to hardcode the result. This would make resetting/presetting challenging, and we'd have to be careful about which cases allow this, but I think it could work for some cases.

And since this logic would only occur on the first call, it should overall be a performance win (and in fact we'd only see the upside in our benchmarks). Would love thoughts @jemmaissroff @ms-ati

**Comment by ms-ati** [comment]
I'm familiar with this idea! This is optimizing to return a literal value, right?

So, right off the bat, @JacobEvelyn do you agree that this approach is fundamentally incompatible with **immutable** objects? 

Or do you see a path forward to supporting this on immutable objects?

**Comment by JacobEvelyn** [comment]
Thanks @ms-ati!

> This is optimizing to return a literal value, right?

Yes, exactly!

> do you agree that this approach is fundamentally incompatible with **immutable** objects?

Yep! I forgot to mention that in my description above but I was assuming we'd branch and only do this if the object is not frozen. I realize now that if an object is frozen _after_ the first method call and then we try to reset the memoization that wouldn't work though. Does that seem like a sufficient edge case to no longer consider this path?

**Comment by ms-ati** [comment]
Yeah, I suggest we give up on this for now @JacobEvelyn
