### ISSUE TITLE
Question: Any test/doc about thread safety when using this gem?

### ISSUE THREAD

**Issue by PikachuEXE** [panorama-ed/memo_wise#184]
I shared this gem on Reddit and someone ask for thread safety:
https://old.reddit.com/r/rails/comments/oglovy/introducing_memowise/

I am not very concerned for my own use but would be good to have something for it.

**Comment by ms-ati** [comment]
Thread-safety of **zero-args** methods
- Pending spec in #225 
- Fix for thread-safety in #224 
- TODO: Document and add spec demonstrating that an unmemoized method may be called multiple times under contention  between threads, and one of the return values will be set as the memoized value
