### ISSUE TITLE
Multiple composition inheritance bug

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#238]
```ruby
module M1
  prepend MemoWise

  def method_to_memowise ; true ; end
  memo_wise :method_to_memowise
end

module M2
  prepend MemoWise

  def other_method_to_memowise ; false ; end
  memo_wise :other_method_to_memowise
end

class C1
  include M1, M2
end

c = C1.new
puts c.method_to_memowise # Should be true
# => true
puts c.other_method_to_memowise # Should be false
# => true
```

I'm not sure if there's an elegant way to fix this. The easy solutions I can think of are:
- Use a global index counter instead of one tied to the class hierarchy [downside: objects will have large/sparse arrays storing results]
- Go back to using hashes keyed on method name instead of arrays [downside: hash accesses are slightly slower than array accesses]

Some "more performant" options that may be difficult:
- Have MemoWise delay the `module_eval` until either (a) the method is called the first time or (b) the object's `freeze` method is called.
- Have MemoWise listen for changes to the ancestor chain and re-`module_eval` some/all methods to avoid index conflicts

**Comment by PikachuEXE** [comment]
You beat me to report this issue lol

My findings:
Maybe as part of optimization [an `index` is used for each class](https://github.com/panorama-ed/memo_wise/blob/v1.3.0/lib/memo_wise.rb#L181)
As the `index` value for `M1` and `M2` on different methods are the same (in different modules)
Mixing both modules and using different methods would cache the result of the 1st called method and incorrectly used in methods from other mixined modules

I don't have anything to add to your proposed fix directions.

**Comment by JacobEvelyn** [comment]
@PikachuEXE we just released v1.4.0, which fixes this issue. Thanks so much for your patience. ❤️

Please try it out and let us know if you encounter any other issues!

**Comment by PikachuEXE** [comment]
Now I am getting random `memo_wise`ed methods returning unexpected values on each request (e.g. `nil` returned for methods with objects, method expected one class returning object of another class)

Not sure how to reproduce with minimal example yet

**Comment by JacobEvelyn** [comment]
Thanks for finding this, @PikachuEXE ! It seems maybe our reasoning behind using arrays was overly optimistic. @jemmaissroff and I will work on both reverting to a safer internal data structure and producing a minimal reproduction of this error to add to our test suite, but in the meantime if you can reproduce it that would be really helpful!

**Comment by JacobEvelyn** [comment]
@PikachuEXE can you see if v1.5.0 fixes these issues?

**Comment by PikachuEXE** [comment]
Ah I am on 2 week leave
I will test this when I get back to work

**Comment by JacobEvelyn** [comment]
Enjoy your time off!

**Comment by PikachuEXE** [comment]
I can no longer find these issue in 1.5.0
But I got a new issue which will be posted soon 😄
