### ISSUE TITLE
Use nested hashes instead of arrays for methods with multiple required arguments

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#244]
This was a suggestion made by @brasic in the RubyConf Discord channel for our talk. The idea is that for a method like `foo(a, b)`, instead of storing the results like this:

```ruby
# @_memo_wise[index_of_foo]
{ [a, b] => memoized_value }
```

we'd store them like this:

```ruby
# @_memo_wise[index_of_foo]
{ a => { b => memoized_value } }
```

our talk implies that this would be faster (hash lookups on array keys are significantly slower, and in the already-memoized case we avoid a new array allocation each time), and in Discord @brasic had a microbenchmark showing this solution to be faster as well.

**Comment by JacobEvelyn** [comment]
@brasic would you be interested in implementing this? (No pressure either way!)

**Comment by brasic** [comment]
@JacobEvelyn I don't have the bandwidth right now but if this is still open over holiday break when I have some free time I will try to take a look!
