### ISSUE TITLE
Release 1.4.0 breaks simple inheritance

### ISSUE THREAD

**Issue by n-rodriguez** [panorama-ed/memo_wise#252]
Code :

```ruby
# frozen_string_literal: true

module NetboxExtractor
  module Netbox
    class Object
      prepend MemoWise

      attr_reader :netbox_object

      def initialize(netbox_object)
        @netbox_object = netbox_object
      end

      ###############
      # NETBOX DATA #
      ###############

      def netbox_data
        netbox_object.raw_data!
      end
      memo_wise :netbox_data

      def netbox_tags
        netbox_data.dig('tags').map { |t| t['slug'] }
      end
      memo_wise :netbox_tags
    end

    class Device < Object
    end

    class VirtualMachine < Object
    end
  end
end
```

Before : 

```ruby
netbox_object = NetboxClientRuby.dcim.devices.first
device = NetboxExtractor::Netbox::Device.new(netbox_object)
puts device.netbox_tags # => ["netbox-synced"]
```

After :

```ruby
netbox_object = NetboxClientRuby.dcim.devices.first
device = NetboxExtractor::Netbox::Device.new(netbox_object)
puts device.netbox_tags # => { "id" => 45, "url" => "http://netbox/api/....json", ... }
```

Here `device.netbox_tags` returns the call to `netbox_data` without the filtering part (`.dig('tags').map { |t| t['slug'] }`)

**Comment by JacobEvelyn** [comment]
Thanks for reporting this, @n-rodriguez, and so sorry for the problematic behavior! I believe this is the same issue as #251, which we have a fix for and we hope to publish a new version to Rubygems within the next few days.

**Comment by ms-ati** [comment]
@n-rodriguez when you have a moment, could you please try version 1.5.0 and hopefully confirm that this issue is fixed?

**Comment by ms-ati** [comment]
@n-rodriguez would it be possible to verify that that latest version of MemoWise fixed your issue?

_Planning to close this issue in two weeks -- on Tue Feb 8, 2022 -- unless we here back that this issue remains unfixed_

**Comment by JacobEvelyn** [comment]
I'm assuming this is fixed. @n-rodriguez please let us know if you continue to experience issues.
