### ISSUE TITLE
Documentation: Add alt_memery & memoist3 to performance comparison table

### ISSUE THREAD

**Issue by pboling** [panorama-ed/memo_wise#338]
You have `memery` in the table already, but it has been nearly dead for a long time.  `alt_memery` is a maintained [fork](https://github.com/AlexWayfer/alt_memery) I've been using in production for a while now, which has hundreds of commits on top of the old `memery` 1.5.0 release.

I'll work on adding `alt_memery` to the comparison table.

**Comment by JacobEvelyn** [comment]
Thanks for sharing! Let me know if you need help adding it.

**Comment by pboling** [comment]
Got it working.  Added [`memoist3`](https://github.com/honzasterba/memoist) (a `memoist` fork with Ruby3 fixes) as well!  PR shortly.

**Comment by pboling** [comment]
@JacobEvelyn it is done in #339
