### ISSUE TITLE
Add YARD documentation

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#34]
- [x] Create the README badge+link, and setup automatic generation on RubyDoc.info for both Github project and (later) published gem
- [x] Instrument the project’s development dependencies so that we can generate docs exactly like RubyDoc.info locally
- [x] Backfill docs so that they look good on RubyDoc.info
- [x] Backfill docs for meta-programmed methods as well
- [x] Take a pass to ensure the YARD linking (to classes and methods) is working
- [x] Ensure code snippets are rendered with Ruby highlighting
- [x] Try to add test coverage of documentation example code snippets, e.g. with https://github.com/p0deje/yard-doctest

**Comment by ms-ati** [comment]
Initial documentation is done!
