### ISSUE TITLE
Broken Readme Links

### ISSUE THREAD

**Issue by ramaboo** [panorama-ed/memo_wise#361]
All the documentation links seem to be broken:

These links:
<img width="963" alt="Screenshot 2024-11-20 at 15 42 25" src="https://github.com/user-attachments/assets/8b02ba9e-8a1b-4c13-9c23-eff4ee8153b7">

Lead to this:
<img width="1516" alt="Screenshot 2024-11-20 at 15 44 12" src="https://github.com/user-attachments/assets/9cf5ace8-b71a-4a2d-80d8-893d7a877f37">

**Comment by JacobEvelyn** [comment]
Thanks for flagging this @ramaboo! It looks like the `MemoWise` module is no longer getting docs generated for it. (https://www.rubydoc.info/github/panorama-ed/memo_wise exists but the "Top Level Namespace" it shows is empty.)

@ms-ati do you have insight into what we need to fix here?

**Comment by ms-ati** [comment]
Thank you @ramaboo. I triggered a regeneration of the RubyDoc.info here:
https://www.rubydoc.info/find/github?q=memo_wise

After clicking the button, I am seeing the links as fixed now -- does it work for you as well?
<img width="28" alt="Screenshot 2024-11-25 at 12 28 06 PM" src="https://github.com/user-attachments/assets/bb2069a0-7c97-41ee-a523-62943b0b2832">

**Comment by ms-ati** [comment]
Closing this as I think it's resolved - please ping again if you disagree
