### ISSUE TITLE
Rework the README and branding

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#37]
- [x] update tagline in gemspec and on GitHub: `The wise choice for Ruby memoization`
- [x] add feature list/unique selling points of our gem:
  - Highest performance + Rigorous benchmarking
  - Preset
  - reset
  - Frozen instances (value objects)
  - Test coverage
  - Well-documented API
- [x] Add other GitHub badges (see examples here: https://github.com/JacobEvelyn/friends)

**Comment by JacobEvelyn** [comment]
@jemmaissroff I'm not sure I totally follow the last item in the checklist:

> Document that changing method visibility must occur before memoizing methods in order to preserve visibility. (See #59 for more detail.)

If I do:

```ruby
memo_wise :foo
private :foo
```

or

```ruby
private :foo
memo_wise :foo
```

isn't the result of both of these the same, i.e. `foo` will be both memoized and private?

**Comment by jemmaissroff** [comment]
@JacobEvelyn re:
> isn't the result of both of these the same, i.e. `foo` will be both memoized and private?
Yes, you're actually totally right. I just ran the tests locally switching the order. But can you explain to me how that's working?

My assumption was that if we made the method private after memoizing it, it wouldn't be private when we check `private_method_defined?` within `#memo_wise`. Can you explain to me why that doesn't matter?

**Comment by JacobEvelyn** [comment]
> Can you explain to me why that doesn't matter?

Sure! In this case:

```ruby
memo_wise :foo
private :foo
```

We're first creating a new _public_ method `foo`, which wraps the behavior of the old ([now-private](https://github.com/panorama-ed/memo_wise/blob/main/lib/memo_wise.rb#L150)) method `foo`. But then on the next line when we call `private :foo` we're making our new memoized method private.

Does that make sense?

**Comment by jemmaissroff** [comment]
> Does that make sense?

Ah yes! So just to confirm my understanding. The order of the `private` and `memo_wise` call will impact what we do internally. But in both cases we'll ultimately have a private memoized method
