### ISSUE TITLE
Allow permanent un-memoization

### ISSUE THREAD

**Issue by JacobEvelyn** [panorama-ed/memo_wise#42]
Give the ability to change the state of a method back to no memoization (i.e. before they called `memo_wise`).

**Comment by ms-ati** [comment]
@JacobEvelyn are we already decided on implementing this? Did we settle on an example use case that motivate it?

And if we are implementing, is this for 1.0 or after?

**Comment by JacobEvelyn** [comment]
Only issues in the [1.0.0 milestone](https://github.com/panorama-ed/memo_wise/milestone/1) are things we agreed were needed for 1.0.0's release. My (fuzzy) recollection of this one is that @ms-ati thought it was a best practice for gems to have a way to completely revert their effects. Do you or @jemmaissroff remember differently?

Personally I don't see a compelling use case for this and would be happy to say we don't want to support it (until we learn of a use case for it). Thoughts?

**Comment by JacobEvelyn** [comment]
We decided to close this until someone requests it or makes a compelling use case for this feature.
